/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      id:'summary',
      label: 'js自我总结',
    },
    {
      type: 'category',
      label: '代理配置',
      collapsible: true,
      collapsed: false,
      items: ['tutorial-nginx/nginx','tutorial-nginx/apache'],
    },
    {
      type: 'category',
      label: 'js系列',
      collapsible: true,
      collapsed: false,
      items: ['tutorial-js/sjms'],
    },
    {
      type: 'category',
      label: '其他杂项',
      collapsible: true,
      collapsed: false,
      items: ['tutorial-other/naming-notations'],
    },
  ],

};

module.exports = sidebars;
